config/routes.rb
Rails.application.routes.draw do
  root to: 'user/home_page#index'
  
  namespace :user do
    resources :products, only: [:index, :show]
    resources :shopping_sessions, only: [:show, :update]
    post '/apply_discount', to: 'shopping_sessions#apply_discount'
    resources :orders, only: [:new, :create]
    resources :cart_items, only: [:create, :show, :destroy]
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  after_save :update_total_session
  
  belongs_to :shopping_session
  belongs_to :product

  def update_total_session
    total = self.shopping_session.cart_items.sum { |cart_item| cart_item.quantity * cart_item.product.price }
    self.shopping_session.update(total: total)
  end
end

app/models/discount.rb
class Discount < ApplicationRecord
    before_create :generate_code

    scope :is_active, -> { where(active: true) }

    def generate_code
        self.code = SecureRandom.hex(4)
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :payment_detail
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment_detail.rb
class PaymentDetail < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :cart_items
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
end

app/models/product_inventory.rb
class ProductInventory < ApplicationRecord
end

app/models/shopping_session.rb
class ShoppingSession < ApplicationRecord
  belongs_to :user
  has_many :cart_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :shopping_session

end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user
end

app/models/user_payment.rb
class UserPayment < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/cart_items_controller.rb
class User::CartItemsController < ApplicationController
    include User::ShoppingSessionsHelper
    before_action :set_cart_item, only: [:show, :destroy]

    def create
        if cart_item = shopping_session.cart_items.find_by(product_id: cart_item_params[:product_id])
            cart_item.update(quantity: cart_item.quantity + cart_item_params[:quantity].to_i)
        else
            cart_item = shopping_session.cart_items.new(cart_item_params)
            render json: { errors: "Can't add item" } unless cart_item.save
        end
        render json: { items_in_cart: items_in_cart }
    end

    def show
        render json: {
            data: ActiveModelSerializers::SerializableResource.new( @cart_item, serializer: CartItemSerializer),
            status: 200,
            type: 'Success'
        }    
    end

    def destroy
        if @cart_item.destroy
            render json: { notice: 'Item was removed' }
        else
            render json: { errors: 'Remove Item failed' }
        end
    end

    private
        def set_cart_item
            @cart_item = CartItem.find(params[:id])
        end

        def cart_item_params
            params.require(:cart_item).permit(:product_id, :quantity)
        end
end

app/controllers/user/home_page_controller.rb
class User::HomePageController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < ApplicationController
    def new
        @shopping_session = current_user.shopping_session
        @cart_items = current_user.shopping_session.cart_items
    end
end

app/controllers/user/products_controller.rb
class User::ProductsController < ApplicationController
    before_action :set_product, only: [:show]
    
    def index
      @products = Product.all
    end

    def show
    end

    private
      def set_product
        @product = Product.find(params[:id])
      end
end

app/controllers/user/shopping_sessions_controller.rb
class User::ShoppingSessionsController < ApplicationController
    include User::ShoppingSessionsHelper
    before_action :authenticate_user!

    def show
        render json: {
            data: ActiveModelSerializers::SerializableResource.new(shopping_session, serializer: ShoppingSessionSerializer),
            status: 200,
            type: 'Success'
        }
    end

    def apply_discount
        discount = Discount.find_by(code: params[:code], active: true)
        if discount
            render json: { percent: discount.percent, status: 'success'}
        else
            render json: { error: "Discount is not available", status: 'error' }
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def custom_bootstrap_flash
        flash_messages = []
        flash.each do |type, message|
          type = 'success' if type == 'notice'
          type = 'error'   if type == 'alert'
          text = "<script>toastr.#{type}('#{message}');</script>"
          flash_messages << text.html_safe if message
        end
        flash_messages.join("\n").html_safe
    end
end

app/helpers/user/cart_items_helper.rb
module User::CartItemsHelper
    def price_for_cart_items cart_item
        sprintf('%.2f',cart_item.quantity * cart_item.product.price)
    end
end

app/helpers/user/home_page_helper.rb
module User::HomePageHelper
end

app/helpers/user/orders_helper.rb
module User::OrdersHelper
end

app/helpers/user/product_helper.rb
module User::ProductHelper
end

app/helpers/user/shopping_sessions_helper.rb
module User::ShoppingSessionsHelper
    def items_in_cart
        current_user.shopping_session.cart_items.sum(:quantity)
    end

    def shopping_session
        current_user.shopping_session
    end
end

app/views/user/cart_items/_cart_item.html.erb
<div id="cart-item-<%= cart_item.id %>" class="card rounded-3 mb-4">
    <div class="card-body p-4">
        <div class="row d-flex justify-content-between align-items-center">
            <div class="col-md-2 col-lg-2 col-xl-2">
            <img
                src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-shopping-carts/img1.webp"
                class="img-fluid rounded-3" alt="Cotton T-shirt">
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3">
                <p class="lead fw-normal mb-2">Basic T-shirt</p>
                <p><span class="text-muted">Size: </span>M <span class="text-muted">Color: </span>Grey</p>
            </div>
            <div class="col-md-3 col-lg-3 col-xl-2 d-flex  quantity-input">
                <button class="btn btn-link px-2"
                    onclick="downQuantity(this.parentNode.querySelector('input[type=number]'))">
                    <i class="fas fa-minus"></i>
                </button>

                <input min="0" name="quantity" value="<%= cart_item.quantity %>" type="number"
                    class="form-control form-control-sm cart-item-input" data-cart-item-id="<%= cart_item.id %>" data-cart-item-price="<%= cart_item.product.price %>"/>

                <button class="btn btn-link px-2"
                    onclick="upQuantity(this.parentNode.querySelector('input[type=number]'))">
                    <i class="fas fa-plus"></i>
                </button>
            </div>
            <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <h5 id="price-for-cart-items" class="mb-0"><%= price_for_cart_items cart_item %> $</h5>
            </div>
            <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                <button href="#!" class="btn btn-link text-danger" onclick="removeItem('<%= cart_item.id %>')"><i class="fas fa-trash fa-lg"></i></button>
            </div>
        </div>
    </div>
</div>

<script>
    function upQuantity(element) {
        element.stepUp()
        setPricePack(element)
        updateTotal()
    }

    function downQuantity(element){
        if (element.value == 1) {
            removeItem(element.dataset.cartItemId)
        }
        else {
            element.stepDown()
            setPricePack(element)
        }
        updateTotal()
    }

    function removeItem(cartItemId) {
        let text = "Remove Item From Order"
        if (confirm(text) == true) {
            document.getElementById(`cart-item-${cartItemId}`).remove()
            remmoveItemBackend(cartItemId)
        }
    }

    function remmoveItemBackend(cartItemId) {
        const csrfToken = document.querySelector("[name='csrf-token']").content
        fetch(`/user/cart_items/${cartItemId}`, {
            method: 'DELETE',
            mode: 'cors',
            cache: 'no-cache',
            credentials: 'same-origin',
            headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': csrfToken
            }
        })
            .then(response => response.json())
            .then(data => {
                console.log(data)
            })
    }
    function updateTotal(){
        let total = Number.parseFloat(getTotalPrice()).toFixed(2)
        document.getElementById("total-price").textContent = `${total} $`
        setSummary()
    }

    function getTotalPrice() {
        let total = 0
        const cartItems = document.getElementsByClassName('cart-item-input')
        for (let i = 0; i < cartItems.length; i++) {
            total += parseInt(cartItems[i].value) * parseInt(cartItems[i].dataset.cartItemPrice)
        }
        return total
    }

    function setPricePack(element){
        const price = Number.parseFloat(parseFloat(element.value) * parseFloat(element.dataset.cartItemPrice)).toFixed(2)
        document.getElementById("price-for-cart-items").textContent  = `${price} $`
    }
</script>

app/views/user/orders/new.html.erb
<section class="h-100" style="background-color: #eee;">
  <div class="container h-100 py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-10">

        <div class="d-flex justify-content-between align-items-center mb-4">
          <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
        </div>
        
        <%= render @cart_items %>

        <div class="card mb-4">
          <div class="card-body p-4 d-flex flex-row">
            <div class="form-outline flex-fill col-sm-7">
              <input type="text" id="discount-code" class="form-control" placeholder="Discound code"  data-discout-percent ="0"/>
            </div>
            <button type="button" class="btn btn-outline-warning btn ms-3" onclick="applyDiscount()">Apply</button>
            <span class="d-flex align-items-center ml-4 text-danger" id="error-message"></span>
          </div>
        </div>

        <div class="card">
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-4">
              <h3 class="fw-normal mb-0 text-black">Total: </h3>
              <h3 class="fw-normal mb-0 text-black" id="total-price" ><%= sprintf('%.2f', @shopping_session.total) %> $</h3>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-4 text-danger">
              <h7 class="fw-normal mb-0 text-black">Discount: </h7>
              <h7 class="fw-normal mb-0 text-black" id="discount-price">- 0.00 $</h7>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-4">
              <h3 class="fw-normal mb-0 text-black">Final:</h3>
              <h3 class="fw-normal mb-0 text-black" id="final-price"><%= @shopping_session.total.to_i %> $</h3>
            </div>
            <button type="button" class="btn btn-block btn-lg btn-submit">Proceed to Pay</button>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>

<script>
  function applyDiscount() {
    const element = document.getElementById("discount-code")
    const total = document.getElementById("")
    const csrfToken = document.querySelector("[name='csrf-token']").content
    fetch(`/user/apply_discount`, {
      method: 'POST',
      mode: 'cors',
      cache: 'no-cache',
      credentials: 'same-origin',
      headers: {
      'Content-Type': 'application/json',
      'X-CSRF-Token': csrfToken
      },
      body: JSON.stringify({ code: element.value })
    })
    .then(response => response.json())
    .then(data => {
      if (data.status == 'error'){
        const errorSpan = document.getElementById('error-message')
        errorSpan.textContent = data.error
        setTimeout(function() {
          errorSpan.textContent = '';
        }, 1500);
      }
      else {
        element.dataset.discoutPercent = data.percent
        setSummary()
      }
      element.value = ''
    })
  }

  function setSummary() {
    let total = parseInt(getTotalPrice())
    let getPercent = parseFloat(document.getElementById("discount-code").dataset.discoutPercent)
    let discount = Number.parseFloat(total*getPercent).toFixed(2)
    let summary = Number.parseFloat(total*(1-getPercent)).toFixed(2)
    document.getElementById('discount-price').textContent = `- ${discount} $`
    document.getElementById('final-price').textContent = `${summary} $`
  }
</script>

app/views/user/partials/_footer.html.erb
<footer>
    <div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="full">
                <div class="logo_footer">
                <a href="/"><%= image_tag("logo.png", height: '50', width: '50') %></a>
                </div>
                <div class="information_f">
                <p><strong>ADDRESS:</strong> 28 White tower, Street Name New York City, USA</p>
                <p><strong>TELEPHONE:</strong> +91 987 654 3210</p>
                <p><strong>EMAIL:</strong> yourmain@gmail.com</p>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
            <div class="col-md-7">
                <div class="row">
                <div class="col-md-6">
                <div class="widget_menu">
                <h3>Menu</h3>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Testimonial</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
                </div>
            </div>
            <div class="col-md-6">
                <div class="widget_menu">
                <h3>Account</h3>
                <ul>
                    <li><a href="#">Account</a></li>
                    <li><a href="#">Checkout</a></li>
                    <li><a href="#">Login</a></li>
                    <li><a href="#">Register</a></li>
                    <li><a href="#">Shopping</a></li>
                    <li><a href="#">Widget</a></li>
                </ul>
                </div>
            </div>
                </div>
            </div>     
            <div class="col-md-5">
                <div class="widget_menu">
                <h3>Newsletter</h3>
                <div class="information_f">
                    <p>Subscribe by our newsletter and get update protidin.</p>
                </div>
                <div class="form_sub">
                    <form>
                        <fieldset>
                            <div class="field">
                            <input type="email" placeholder="Enter Your Mail" name="email" />
                            <input type="submit" value="Subscribe" />
                            </div>
                        </fieldset>
                    </form>
                </div>
                </div>
            </div>
            </div>
        </div>
    </div>
    </div>
</footer>
<!-- footer end -->
<div class="cpy_">
    <p class="mx-auto">© 2021 All Rights Reserved By <a href="https://html.design/">Free Html Templates</a><br>
    
    Distributed By <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
    
    </p>
</div>

app/views/user/partials/_header.html.erb
<header class="header_section">
    <div class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="/"><%= image_tag("logo.png", height: '50', width: '50') %></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                <li class="nav-item active">
                    <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Pages <span class="caret"></span></a>
                </li>
                <li class="nav-item">
                    <%= link_to "Product", user_products_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=#">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
                <form class="form-inline">
                    <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                    <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                </form>
                <li class="nav-item" data-controller="cart">
                    <%= link_to "CART(#{items_in_cart})", new_user_order_path, class: "nav-link", id: "cart" %>
                </li>
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label"><%= current_user.username %><span class="caret"></span></a>
                    </li>
                <% end %>
                </ul>
            </div>
        </nav>
    </div>
</header>

app/views/user/products/_product.html.erb
<div class="col-sm-6 col-md-4 col-lg-4" data-controller="cart">
    <div class="box">
        <div class="option_container">
        <div class="options">
            <a class="option1" data-action="click->cart#add_item">
            Add To Cart
            </a>
            <a href="" class="option2">
            Buy Now
            </a>
        </div>
        </div>
        <div class="img-box">
        <%= image_tag("logo.png", height: '50', width: '50') %>
        </div>
        <div class="detail-box">
        <h5>
            <%= product.name %>
        </h5>
        <h6>
            $<%= product.price %>
        </h6>
        <input type="hidden" data-cart-target="product" value="<%= product.id %>" >
        <input type="hidden" data-cart-target="shopping_session" value="<%= current_user.shopping_session.id %>" >
        </div>
    </div>
</div>

app/views/user/products/index.html.erb
<!-- inner page section -->
<section class="inner_page_head">
    <div class="container_fuild">
    <div class="row">
        <div class="col-md-12">
            <div class="full">
                <h3>Product Grid</h3>
            </div>
        </div>
    </div>
    </div>
</section>
<!-- end inner page section -->
<!-- product section -->
<section class="product_section layout_padding">
    <div class="container">
    <div class="heading_container heading_center">
        <h2>
            Our <span>products</span>
        </h2>
    </div>
    <div class="row">
        <%= render @products %>
    </div>
    <div class="btn-box">
        <a href="">
        View All products
        </a>
    </div>
    </div>
</section>
<!-- end product section -->
<!-- footer section -->